# Generated by Django 6.0.4 on 2026-05-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_temporalgrant_unlock_at_temporalgrant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporalgrant',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
