# Generated by Django 6.0.4 on 2026-05-01 21:34

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_temporalgrant_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporalgrant',
            name='token',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True),
        ),
    ]
