# Generated by Django 6.0.4 on 2026-06-07 07:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_temporalgrant_opened_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporalgrant',
            name='token',
            field=models.CharField(default=core.models.generate_token, max_length=22, unique=True),
        ),
    ]
